[package]
name = "nozomi"
version = "1.0.0"
edition = "2021"
authors = ["Sans-Atout <augustin.rousset-rouviere@isep.fr>"] 
description = "A rust wipper library"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[lib]
#path = "src/libs.rs"
#crate-type = ["lib"] 
#bench = false

[dependencies]
rand = "0.8.5"