[package]
name = "nozomi"
version = "1.0.1"
edition = "2021"
authors = ["Sans-Atout <augustin.rousset-rouviere@isep.fr>"] 
description = "A rust wipper library"
license = "GPL-3.0"
repository = "https://github.com/Sans-Atout/Nozomi/"

[dependencies]
rand = "0.8.5"