[package]
name = "nozomi"
version = "2.0.1"
edition = "2021"

authors = ["Sans-Atout <augustin.rousset-rouviere@isep.fr>"]
description = "Equivalent of the Linux shred command but in rust and library. Allows you to securely erase data from a hard drive."
keywords = ["security", "erase", "eraser", "wipping", "wipper"]

license = "GPL-3.0"
repository = "https://github.com/Sans-Atout/Nozomi/"

[dependencies]
error-stack = {version = "0.4.1",optional=true}
log = { version = "0.4.21", optional=true}
rand = "0.8.5"
md5 = { version = "0.7.0", optional=true}

[lints.rust]
unsafe_code="forbid"

[dev-dependencies]
pretty_assertions = "1.4.0"

[features]
error-stack = ["dep:error-stack"]
log = ["dep:log"]
secure_log = ["log","dep:md5"]
