name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions/checkout@v2
      - name: Install rust auditing tools
        run: cargo install cargo-audit
      - name : Install cargo-nextest
        run: cargo install cargo-nextest
      - name : Build
        run: cargo build --verbose
      - name : Clippy
        run: cargo clippy --verbose -- -D warnings
      - name: Audit
        run: cargo audit
      - name: Test
        run: ./test.sh

