name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on:  ubuntu-latest
    steps:
      - name: Install Rust
        uses: actions/checkout@v2
      - name: Install nextest
        run: cargo install cargo-nextest    
      - name: Test normal
        run: cargo nextest run
      - name: Test error-stack features
        run: cargo nextest run --features error-stack
      - name: Test log + error-stack features
        run: cargo nextest run --features error-stack,log
      - name: Test secure_log + error-stack features
        run: cargo nextest run --features error-stack,secure_log
      - name: Test secure_log features
        run: cargo nextest run --features secure_log
      - name: Test log features
        run: cargo nextest run --features log